import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/homepageone">HomePageOne</Link>
        </li>
        <li>
          <Link to="/tcnicaspage02">TcnicasPage02</Link>
        </li>
        <li>
          <Link to="/sobrenspagethree">SobrensPageThree</Link>
        </li>
        <li>
          <Link to="/buscarpagefour">BuscarPageFour</Link>
        </li>
        <li>
          <Link to="/mapapagefive">MapaPageFive</Link>
        </li>
        <li>
          <Link to="/mapapagesix">MapaPageSix</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
